name: kr_ui
description: "Premium glassmorphic, Elegant, Simple & Clean UI components. Beautiful, customizable widgets with iOS-style frosted glass effects. Pure Flutter, zero dependencies."
version: 0.0.2+1
homepage: https://www.youtube.com/@king_rittik
repository: https://github.com/RittikSoni/kr_ui
issue_tracker: https://github.com/RittikSoni/kr_ui/issues
documentation: https://github.com/RittikSoni/kr_ui#readme
license: MIT

screenshots:
  - description: 'kr_ui logo'
    path: 'screenshots/krui-banner.png'

platforms:
  android:
  ios:
  web:
  linux:
  windows:
  macos:

funding:
  - https://github.com/sponsors/RittikSoni

topics:
  - ui
  - glassmorphism
  - components
  - widgets
  - material-ui

keywords:
  - ui
  - glassmorphism
  - components
  - widgets
  - design
  - kingrittik
  - rittiksoni
  - king_rittik
  - rittik_soni
  - ui_kit
  - flutter_kit
  - widget
  - shadcn
  - material ui
  

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - assets/
  #   - assets/logo/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
